### ISSUE TITLE
CUDA out of memory during training

### ISSUE THREAD

**Issue by OmarBazaraa** [nmhkahn/CARN-pytorch#11]
I'm getting this RuntimeError during the training process using the following command

```
python carn\train.py --patch_size 32 --batch_size 32 --max_steps 600000 --print_interval 50 --decay 400000 --model carn --ckpt_name carn_test --ckpt_dir checkpoint\carn --scale 2
```

```
Traceback (most recent call last):
  File "carn\train.py", line 52, in <module>
    main(cfg)
  File "carn\train.py", line 48, in main
    solver.fit()
  File "C:\Users\Omar\Desktop\CARN-pytorch\carn\solver.py", line 95, in fit
    psnr = self.evaluate("dataset/Urban100", scale=cfg.scale, num_step=self.step)
  File "C:\Users\Omar\Desktop\CARN-pytorch\carn\solver.py", line 136, in evaluate
    sr = self.refiner(lr_patch, scale).data
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Omar\Desktop\CARN-pytorch\carn\model\carn.py", line 74, in forward
    b3 = self.b3(o2)
  File "C:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Omar\Desktop\CARN-pytorch\carn\model\carn.py", line 30, in forward
    c3 = torch.cat([c2, b3], dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 195.25 MiB (GPU 0; 4.00 GiB total capacity; 2.88 GiB already allocated; 170.14 MiB free; 2.00 MiB cached)
```

**Comment by nmhkahn** [comment]
Hi.
We've only tested on the 1080ti and TITAN X which have more than 10GB memory.
Reducing the batch size might be helpful in this case.

**Comment by OmarBazaraa** [comment]
I reduced the batch size to 1 and still the same problem!

**Comment by nmhkahn** [comment]
What's your GPU and VRAM?

**Comment by OmarBazaraa** [comment]
Nvidia GTX 960M 4GB VRAM

**Comment by nmhkahn** [comment]
Oh, OOM occurs when you evaluate using test data.
Try to change [here](https://github.com/nmhkahn/CARN-pytorch/blob/master/carn/solver.py#L136)
```python
# run refine process in here!
sr = self.refiner(lr_patch, scale).data
```
to
```python
# run refine process in here!
with torch.no_grad():
    sr = self.refiner(lr_patch, scale).data
```
