### ISSUE TITLE
Not able to train the model

### ISSUE THREAD

**Issue by gitman88** [nmhkahn/CARN-pytorch#13]
I am not able to train the model. The command used:

`python carn/train.py --patch_size 64 --batch_size 64 --max_steps 600000 --decay 400000 --model carn --ckpt_name carn --ckpt_dir checkpoint/carn`

And this is the output:

`{
    "batch_size": 64,
    "ckpt_dir": "checkpoint/carn",
    "ckpt_name": "carn",
    "clip": 10.0,
    "decay": 400000,
    "group": 1,
    "loss_fn": "L1",
    "lr": 0.0001,
    "max_steps": 600000,
    "model": "carn",
    "num_gpu": 1,
    "patch_size": 64,
    "print_interval": 1,
    "sample_dir": "sample/",
    "scale": 2,
    "shave": 20,
    "train_data_path": "dataset/DIV2K_train.h5",
    "verbose": "store_true"
}
# of params: 964187
/home/workspace/sisr/CARN-pytorch/carn/solver.py:85: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(self.refiner.parameters(), cfg.clip)
`

After this nothing happens, it seems to be stuck. The process is still running and memory is allocated.

Any ideas what the problem could be?

**Comment by pliu6** [comment]
The training should be ongoing, just no log message.
You can check the checkpoint folder after 10 minutes to see the progress.

**Comment by Auth0rM0rgan** [comment]
Hey @nmhkahn,
It would be nice if you add the log message to your code so we can see the progress. Also, I think the way you are loading the argparse is not efficient since If I change the default parameters in the train.py nothing gonna change so need to write the parameters in the terminal to accept it.

**Comment by idealboy** [comment]
> I am not able to train the model. The command used:
> 
> `python carn/train.py --patch_size 64 --batch_size 64 --max_steps 600000 --decay 400000 --model carn --ckpt_name carn --ckpt_dir checkpoint/carn`
> 
> And this is the output:
> 
> `{ "batch_size": 64, "ckpt_dir": "checkpoint/carn", "ckpt_name": "carn", "clip": 10.0, "decay": 400000, "group": 1, "loss_fn": "L1", "lr": 0.0001, "max_steps": 600000, "model": "carn", "num_gpu": 1, "patch_size": 64, "print_interval": 1, "sample_dir": "sample/", "scale": 2, "shave": 20, "train_data_path": "dataset/DIV2K_train.h5", "verbose": "store_true" } of params: 964187 /home/workspace/sisr/CARN-pytorch/carn/solver.py:85: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_. nn.utils.clip_grad_norm(self.refiner.parameters(), cfg.clip)`
> 
> After this nothing happens, it seems to be stuck. The process is still running and memory is allocated.
> 
> Any ideas what the problem could be?

I think you should set the verbose parameter == True befor beginning trainning, and then, the solver.py only record the event, I think you shoud write some aiding code to print the psnr at each interval.

eg:

                if cfg.verbose and self.step % cfg.print_interval == 0:
                    if cfg.scale > 0:
                        psnr = self.evaluate("dataset/DIV2K", scale=cfg.scale, num_step=self.step)
                        self.writer.add_scalar("DIV2K", psnr, self.step)
                    else:    
                        psnr = [self.evaluate("dataset/DIV2K", scale=i, num_step=self.step) for i in range(2, 5)] 
                        self.writer.add_scalar("DIV2K_2x", psnr[0], self.step)
                        self.writer.add_scalar("DIC2K_3x", psnr[1], self.step)
                        self.writer.add_scalar("DIV2K_4x", psnr[2], self.step)
                    print ("Iteration %d : psnr-2X : %s" % (self.step, str(psnr[0])))
                    print ("Iteration %d : psnr-3X : %s" % (self.step, str(psnr[1])))
                    print ("Iteration %d : psnr-4X : %s" % (self.step, str(psnr[2])))

**Comment by chensiyu1120** [comment]
> 培训应该持续进行，只是没有日志消息。您可以在 10 分钟后检查检查点文件夹以查看进度。
Hello, may I ask why there is an error after I run this command? Looking forward to your reply.

Traceback (most recent call last):
  File "carn/train.py", line 52, in <module>
    main(cfg)
  File "carn/train.py", line 48, in main
    solver.fit()
  File "/data1/home/chensiyu/CARN-pytorch-master/carn/solver.py", line 80, in fit
    sr = refiner(lr, scale)
  File "/data1/home/chensiyu/.conda/envs/CARN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/home/chensiyu/.conda/envs/CARN/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data1/home/chensiyu/.conda/envs/CARN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/home/chensiyu/CARN-pytorch-master/carn/model/carn.py", line 62, in forward
    x = self.sub_mean(x)
  File "/data1/home/chensiyu/.conda/envs/CARN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/home/chensiyu/CARN-pytorch-master/carn/model/ops.py", line 29, in forward
    x = self.shifter(x)
  File "/data1/home/chensiyu/.conda/envs/CARN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/home/chensiyu/.conda/envs/CARN/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight[3, 3, 1, 1], so expected input[64, 64, 64, 3] to have 3 channels, but got 64 channels instead
