### ISSUE TITLE
index out

### ISSUE THREAD

**Issue by yucongzhao1** [nmhkahn/CARN-pytorch#44]
IndexError: Traceback (most recent call last):
  File "/home/zyc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zyc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zyc/tensorflow/SR分析/CARN/CARN-pytorch/carn/dataset.py", line 66, in __getitem__
    item = [(self.hr[index], self.lr[i][index]) for i, _ in enumerate(self.lr)]
  File "/home/zyc/tensorflow/SR分析/CARN/CARN-pytorch/carn/dataset.py", line 66, in <listcomp>
    item = [(self.hr[index], self.lr[i][index]) for i, _ in enumerate(self.lr)]
IndexError: list index out of range
@nmhkahn  I don't know what to do. Can you help me

**Comment by Jiaqi-WANG** [comment]
Hi did you solve this problem?
If so, could you tell me how?

**Comment by Tracy-git** [comment]
maybe you should make a correct DIV2K_train.h5

**Comment by leoyjTu** [comment]
看一下你生成.h5文件的时候，DIV2K下是否有对应的低分辨率图像 DIV2K_train_LR_bicubic/X2、X3、X4和DIV2K_valid_LR_bicubic/X2、X3、X4
