### ISSUE TITLE
Error(s) in loading state_dict for Net: Missing key(s) in state_dict

### ISSUE THREAD

**Issue by Ji-qing** [nmhkahn/CARN-pytorch#9]
Hi, thanks for your codes.
I trained a checkpoint model named carn_m_180000.pth, but when I testing it by sample.py, I got following error, could you give me some suggestions?

```
$ python3 carn/sample.py --model=carn_m --ckpt_path=./checkpoint/carn_m/carn_m_180000.pth --sample_dir=./sample/
using this model
{
    "ckpt_path": "./checkpoint/carn_m/carn_m_180000.pth",
    "cuda": false,
    "group": 1,
    "model": "carn_m",
    "sample_dir": "./sample/",
    "scale": 2,
    "shave": 20,
    "test_data_dir": "dataset/DIV2K_valid_LR_bicubic/X2"
}
Traceback (most recent call last):
  File "carn/sample.py", line 122, in <module>
    main(cfg)
  File "carn/sample.py", line 110, in main
    net.load_state_dict(new_state_dict)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "upsample.up2.body.0.bias", "upsample.up2.body.0.weight", "upsample.up3.body.0.bias", "upsample.up3.body.0.weight", "upsample.up4.body.0.bias", "upsample.up4.body.0.weight", "upsample.up4.body.3.bias", "upsample.up4.body.3.weight". 
	Unexpected key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias". 
```

**Comment by Ji-qing** [comment]
multi_scale should be set False.
but I got similar error 
```
RuntimeError: Error(s) in loading state_dict for Net:
	Unexpected key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias". 

```

**Comment by nmhkahn** [comment]
It's hard to debug without a checkpoint file.
How about print the k(name) in state_dict.items() for the "network"?
You can compare to the checkpoint's to check what's missing or not.

**Comment by Ji-qing** [comment]
https://github.com/nmhkahn/CARN-pytorch/blob/160a4bc444dd0acfa4bbe93e5f8e45e9cd551c22/carn/sample.py#L96
It missed a parameter `scale=cfg.scale`. And `multi-scale `should be` False `if you did not use cfg.multi_scale
